controller.up.onEvent(ControllerButtonEvent.Repeated, function () {
    mySprite.y += -5
})
controller.right.onEvent(ControllerButtonEvent.Repeated, function () {
    mySprite.x += 5
})
controller.down.onEvent(ControllerButtonEvent.Repeated, function () {
    mySprite.y += 5
})
controller.left.onEvent(ControllerButtonEvent.Repeated, function () {
    mySprite.x += -5
})
let mySprite: Sprite = null
scene.setBackgroundColor(1)
mySprite = sprites.create(img`
    ........................
    ......ffff..............
    ....fff22fff............
    ...fff2222fff...........
    ..fffeeeeeefff..........
    ..ffe222222eef..........
    ..fe2ffffff2ef..........
    ..ffffeeeeffff..........
    .ffefbf44fbfeff.........
    .fee41fddf14eef.........
    fdfeeddddd4eff..........
    fbffee444edd4e..........
    fbf4f2222edde...........
    fcf.f22cccee............
    .ff.f44cdc4f............
    ....fffddcff............
    .....fddcff.............
    ....cddc................
    ....cdc.................
    ....cc..................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
